services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    command: npm run start:dev

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

volumes:
  redis:
    driver: local

networks:
  backend:
    driver: bridge
